/// Flutter icons Address
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Address
///      fonts:
///       - asset: fonts/Address.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Address {
  Address._();

  static const _kFontFam = 'Address';
  static const _kFontPkg = null;

  static const IconData map_signs = IconData(0xf277, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
